---
title: Your awesome title
email: your-email@domain.com
description: |
  Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
baseurl: "/test-jekyll"
url: http://example.com
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
permalink: "/:collection/:title"
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    author: Mr. Jack
    categories: 
    summary: ''
    keywords: ''
- scope:
    path: ''
    type: pages
  values:
    layout: default
    summary: ''
    keywords: ''
timezone: America/Halifax
