---
upload_path: "/cats"
frontmatter_file_url_template: "/test-jekyll/cats"
body_file_url_template: "/test-jekyll/cats"
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
collections: 
